### ISSUE TITLE
Library Card Number

### ISSUE THREAD

**Issue by MariaMa-GitHub** [MariaMa-GitHub/group_project#2]
@BashirKad One of the methods that I have to write for the Person class is getLibraryCard(). In the beginning, I have designed it to generate a card number based on the number of people registered at a library (specific), but then I realized that there could be multiple libraries (instances of the Library class) so that wouldn't work.

I guess that you can create a static variable for the Library class (e.g. static int num_total_person = 0;) that counts the **total** number of people registered at libraries (**all of them**, not a specific one). So every time that someone gets registered in a library (**no matter which one**) this variable increments by one and based on that I can assign a card number to that person.

**Comment by BashirKad** [comment]
Sorry I haven't had internet for the past however long, but yeah I'll make sure to add that. Also I think you closed your other comment amount the max items that someone can borrow and the way I had it thought out was that if we're implementing a queue system, then we can only have 1 item on hold, otherwise we would need to dequeue Person(s) not from the start of the line and it wouldn't act as a queue.
If we wanted to do it like you said then we just need to change our idea of a queue into a normal linked list which really doesn't affect anything else and its whatever you guys prefer. It just means that the Media class also needs a variable called "total" or something like that that decreases until it reaches 0 for each copy that is checked out.

**Comment by MariaMa-GitHub** [comment]
About the issue that I closed, I deleted it because I realized that it's better as it is right now. I made it so that each person can borrow a maximum of [x] items **in total (no matter from which library)**. I realized it's so much simpler because we wouldn't have to track to which library do each of the items belongs.

**Comment by BashirKad** [comment]
Oh sorry, I misunderstood what you meant in the first issue, but no worries, we'll just keep it simple and do it like that
